apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-html
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  index.html: |
    {{- .Values.htmlContent | nindent 4 }}